# @name Get all Fulfilled requests
GET localhost:3000/fulfilled

###

# @name Get single Fulfilled request
GET localhost:3000/fulfilled/{{}}

###

# @name Add product to inventory
POST localhost:3000/inventory
Content-Type: application/json

{ "productId": "test", "quantity": 10 }

###

# @name Get all Requests
GET localhost:3000/requests

###

# @name Add request
POST localhost:3000/requests
Content-Type: application/json

{ "productId": "test", "quantity": 3 }

###

# @name Get single Request
GET localhost:3000/requests/{{}}

###

# @name Get Report
GET localhost:3000/report