cassandra:
  contact-points: 127.0.0.1
  port: ${CASSANDRA_PORT:9042}
  schema-action: create_if_not_exists
  local-datacenter: datacenter1
  keyspace-name: test2
  replicationFactor: 2

  update-delay: 1000
  max-iterations: 10

application:
  id: ${APP_ID:1}

spring:
  cassandra:
    schema-action: create_if_not_exists